"""Schemas package initialization"""

from app.schemas.auth_schemas import (
    LoginRequest,
    RefreshTokenRequest,
    Token,
    TokenPayload,
)
from app.schemas.schemas import (
    DealBase,
    DealCreate,
    DealResponse,
    DealStatus,
    DealUpdate,
    HealthCheck,
    UserBase,
    UserCreate,
    UserResponse,
    UserUpdate,
)
from app.schemas.user_preferences import (
    BudgetRange,
    CarPreferences,
    CarType,
    FuelType,
    NotificationPreferences,
    SavedSearch,
    SavedSearchCreate,
    SavedSearchResponse,
    SearchPreferences,
    TransmissionType,
    UserPreferencesBase,
    UserPreferencesCreate,
    UserPreferencesResponse,
    UserPreferencesUpdate,
)

__all__ = [
    "DealBase",
    "DealCreate",
    "DealUpdate",
    "DealResponse",
    "DealStatus",
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "HealthCheck",
    "Token",
    "TokenPayload",
    "LoginRequest",
    "RefreshTokenRequest",
    "BudgetRange",
    "CarPreferences",
    "CarType",
    "FuelType",
    "TransmissionType",
    "NotificationPreferences",
    "SearchPreferences",
    "UserPreferencesBase",
    "UserPreferencesCreate",
    "UserPreferencesUpdate",
    "UserPreferencesResponse",
    "SavedSearch",
    "SavedSearchCreate",
    "SavedSearchResponse",
]
